version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    networks: 
        - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks: 
        - elastic-network
        
networks:
    elastic-network:
        driver: bridge
        