 output.elasticsearch:
  hosts: ["localhost:9200"]
  
filebeat.prospectors:
- type: log
  enabled: true
  paths:
  - '/var/lib/docker/containers/*/*.log'
output.elasticsearch:
  hosts: ["localhost:9200"]